on:
  push:
    branches:
      - master

jobs:
  deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: Deploy Website
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/path/to/project && git pull git@github.com:project/home.git        
      - name: Docker Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/path/to/project && docker built -t <container> .